version: "3.9"
services:
  front:
    image: httpd:alpine
    ports:
      - 83:80
    volumes:
      - './Client:/usr/local/apache2/htdocs/'

  back:
    image: node:16-alpine
    working_dir: /root/InsertGenerator
    ports:
      - 84:81
    volumes:
      - './Server:/root/InsertGenerator'
    command: [npm, start]
    tty: true