version: "2.3"
services:
  front:
    image: httpd:alpine
    ports:
      - 83:80
    volumes:
      - './Client:/usr/local/apache2/htdocs/'

  back:
    build: ./Server
    working_dir: /home/node/InsertGenerator
    ports:
      - 84:81
    volumes:
      - './Server:/home/node/InsertGenerator'
    command: [npm, start]
    tty: true
